limebit/medmodels

- medmodels/treatment_effect_estimation/report.py
There was no way of knowing the keys of the dictionary returned by `full_report` (except for checking the function itself). I replaced it with a typed dictionary. The keys are now statically typed and are available in auto completion
> refactor: full treatment effect report now returns typed dictionary

- crates/medmodels-core/src/medrecord/graph/mod.rs
- crates/medmodels-core/src/medrecord/mod.rs
> fix: `remove_node` now removes removed edges from `group_mapping`

- medmodels/medrecord/builder.py
- medmodels/medrecord/medrecord.py
- medmodels/medrecord/tests/test_builder.py
- medmodels/medrecord/tests/test_medrecord.py
The add_nodes function now allows for adding nodes directly to a group with the function.
```python
medrecord = MedRecord()
medrecord.add_nodes(nodes, group)
```
> feat: Allow adding/appending to groups when adding nodes or edges

- medmodels/treatment_effect/estimate.py
- medmodels/treatment_effect/report.py
- medmodels/treatment_effect/tests/test_treatment_effect.py
The previously named "absolute risk" function in the TreatmentEffect Estimate module was wrongly named like that. The implementation corresponded actually to "absolute risk reduction".
> fix: Renaming absolute risk function for correct one (absolute risk reduction)

- medmodels/treatment_effect/continuous_estimators.py
- medmodels/treatment_effect/estimate.py
- medmodels/treatment_effect/tests/test_continuous_estimators.py
- medmodels/treatment_effect/tests/test_treatment_effect.py
- medmodels/treatment_effect/treatment_effect.py
Added a function that better visualizes how the different control and treated groups are separated. It is in `subject_counts`.
Also renamed the following variables everywhere for clarity purposes:
- treatment_true: "treatment_outcome_true"
- treatment_false: "treatment_outcome_false"
- control_true: "treatment_control_true"
- control_false: "treatment_control_false"
``` python
TretmentEffect.estimate.print_contingency_table(medrecord)
```
```
-----------------------------------
Outcome   
Group           True     False   
-----------------------------------
Treated         2        1       
Control         3        3       
-----------------------------------
```
> feat: Adding contingency table print and treatment groups variables renaming

- docs/user_guide/getstarted.md
- medmodels/_medmodels.pyi
- medmodels/medrecord/builder.py
- medmodels/medrecord/medrecord.py
- medmodels/medrecord/tests/test_builder.py
- medmodels/medrecord/tests/test_medrecord.py
- medmodels/medrecord/types.py
- medmodels/treatment_effect/tests/test_temporal_analysis.py
- rustmodels/src/medrecord/mod.rs
Removed functions:
- `add_node`
- `add_edge`
Renamed functions:
- `remove_node` -> `remove_nodes`
- `remove_edge` -> `remove_edges`
- `remove_group` -> `remove_groups`
- `add_node_to_group` -> `add_nodes_to_group`
- `add_edge_to_group` -> `add_edges_to_group`
- `remove_node_from_group` -> `remove_nodes_from_group`
- `remove_edge_from_group` -> `remove_edges_from_group`
**For testing, a `make install-dev` action is required!**
> feat: removing singular name functions and changing them to plural naming

- crates/medmodels-core/src/medrecord/querying/attributes/operation.rs
- crates/medmodels-core/src/medrecord/querying/edges/operation.rs
- crates/medmodels-core/src/medrecord/querying/nodes/operation.rs
- crates/medmodels-core/src/medrecord/querying/values/operation.rs
This fixes a bug where operations that change the value of an operand (e.g. `.add(...)`, `.subtract(...)`, `.round()` etc.) are not applied correctly when the operand is used in a comparison
> fix: comparison operations now correctly evaluate operand

- medmodels/medrecord/_overview.py
- medmodels/medrecord/schema.py
- medmodels/medrecord/tests/test_medrecord.py
- medmodels/medrecord/tests/test_overview.py
- medmodels/medrecord/tests/test_schema.py
- medmodels/treatment_effect/continuous_estimators.py
- medmodels/treatment_effect/matching/propensity.py
- medmodels/treatment_effect/matching/tests/test_metrics.py
- medmodels/treatment_effect/matching/tests/test_propensity_score.py
- medmodels/treatment_effect/tests/test_continuous_estimators.py
- medmodels/treatment_effect/tests/test_temporal_analysis.py
- medmodels/treatment_effect/tests/test_treatment_effect.py
- medmodels/treatment_effect/treatment_effect.py
- pyproject.toml
disabled docstring linting for files in `tests/*` and for `__init__.py`
Also applied auto-formatting.
The only thing that was actually changed in this PR is the `pyproject.toml`
If this is not intended, it can be easily undone @FloLimebit
> refactor: disable docstring linting for tests and __init__

- medmodels/treatment_effect/estimate.py
- medmodels/treatment_effect/matching/matching.py
- medmodels/treatment_effect/matching/neighbors.py
- medmodels/treatment_effect/matching/propensity.py
- medmodels/treatment_effect/temporal_analysis.py
- medmodels/treatment_effect/tests/test_continuous_estimators.py
- medmodels/treatment_effect/tests/test_temporal_analysis.py
- medmodels/treatment_effect/tests/test_treatment_effect.py
- medmodels/treatment_effect/treatment_effect.py
- Eliminated `find_node_in_time_window` (not needed anymore in that format) and refactored into the `TreatmentEffect` class as "_query_node_within_time_window".
- Changed "treated_group" and "control_group" variables into "treated_set" and "control_set" in all TEE files since they might lead to confusion. Also, changed a couple variable names that should have been changed in previous PRs but were forgotten.
- Changed datatypes and error messages in tests for new query.
Note:
- Some errors used as sanity checks were eliminated from the TreatmentEffect because of the implementation of the Query Engine. These should be re-implemented after issue #100
> refactor: optimize treatment effect and associated functions with new query engine

- medmodels/medrecord/medrecord.py
The MedRecord can have loads of different nodes and groups, so going through their attributes can be very slow work. This can hinder the performance of the MedRecord in debugging mode. For that reason, a short representation of the MedRecord will be shown in debugging mode> 
`<MedRecord: 73 nodes, 160 edges>`
> refactor: fast-computed representation of the MedRecord when in debugging mode

- medmodels/medrecord/medrecord.py
- medmodels/treatment_effect/builder.py
- medmodels/treatment_effect/continuous_estimators.py
- medmodels/treatment_effect/estimate.py
- medmodels/treatment_effect/matching/algorithms/classic_distance_models.py
- medmodels/treatment_effect/matching/algorithms/propensity_score.py
- medmodels/treatment_effect/matching/covariates/metrics.py
- medmodels/treatment_effect/matching/matching.py
- medmodels/treatment_effect/matching/neighbors.py
- medmodels/treatment_effect/matching/propensity.py
- medmodels/treatment_effect/matching/tests/test_metrics.py
- medmodels/treatment_effect/matching/tests/test_propensity_score.py
- medmodels/treatment_effect/report.py
- medmodels/treatment_effect/temporal_analysis.py
- medmodels/treatment_effect/tests/test_continuous_estimators.py
- medmodels/treatment_effect/tests/test_temporal_analysis.py
- medmodels/treatment_effect/tests/test_treatment_effect.py
- medmodels/treatment_effect/treatment_effect.py
Fixing linting and dosctrings in all treatment effect files. Some rework was done in `continuous.estimators.py` to add hedges_g since the add_correction boolean argument was against linting conventions.
> fix: linting and docstrings issues in treatment effect module

- medmodels/medrecord/_overview.py
- medmodels/medrecord/medrecord.py
- medmodels/medrecord/tests/test_medrecord.py
- medmodels/medrecord/tests/test_overview.py
- medmodels/medrecord/types.py
Closes Ticket #260 
Added Input parameter `groups` to `overview_edges()` and `overview_nodes()` to only show specified groups.
Also fixed key word min/max showing for temporal attributes.
Updated tests.
> feat: added group input variable and fixed table

- Cargo.lock
- Cargo.toml
Can be merged after #297 
The "culprit" for the bug can be found in: https://github.com/pola-rs/polars/blob/main/crates/polars-core/src/series/from.rs#L208
The conversion from arrow arrays to polars series is only enabled for some datatypes by default. The others need to be enabled using feature flags.
---
**Note:**
We will not include any tests for this behaviour as this would test behaviour that was not written by us, but by the `polars` team. To achieve theoretical test coverage on our side, we'd need to test every permutation of every data-type and check if the dataframe can be transferred from python to rust "space", which would use their code.
> fix: add polars support for all datatypes

- .github/workflows/formatting.yml
- .github/workflows/linting.yml
- .github/workflows/testing.yml
- README.md
- docs/developer_guide/setup.md
- docs/index.md
- medmodels/_medmodels.pyi
- medmodels/medrecord/_overview.py
- medmodels/medrecord/builder.py
- medmodels/medrecord/datatype.py
- medmodels/medrecord/querying.py
- medmodels/medrecord/types.py
- medmodels/treatment_effect/continuous_estimators.py
- medmodels/treatment_effect/matching/algorithms/propensity_score.py
- medmodels/treatment_effect/matching/matching.py
- medmodels/treatment_effect/tests/test_temporal_analysis.py
- medmodels/treatment_effect/treatment_effect.py
- pyproject.toml
Removed python 3.9 from the supported list and refactored code to no longer inclue the sys.version checks. Also added support for python 3.13
> chore: Drop support for python 3.9 and add support for 3.13

- medmodels/treatment_effect/estimate.py
- medmodels/treatment_effect/matching/algorithms/propensity_score.py
- medmodels/treatment_effect/matching/matching.py
- medmodels/treatment_effect/matching/neighbors.py
- medmodels/treatment_effect/matching/propensity.py
- medmodels/treatment_effect/matching/tests/test_matching.py
- medmodels/treatment_effect/matching/tests/test_propensity_score.py
- medmodels/treatment_effect/treatment_effect.py
- Essential covariates are no longer "gender" and "age" by default, but all attributes from the patients group. Raises errors in case there are not enough control/treated patients with those attributes.
- One-hot-encoded variables are not "gender" by default, but all attributes characterised by `extract_attribute_summary` function as Categorical.
- Added tests to the Matching Class
- Changed some variable names (hyperparam -> hyperparameters) for better variable naming consistency.
> fix: the way essential covariates and one-hot-encoded ones are processed

- docs/developer_guide/docstrings.md
- docs/index.md
- medmodels/medrecord/medrecord.py
- medmodels/medrecord/querying.py
- medmodels/treatment_effect/estimate.py
This branch fixes critical and non-critical bugs in docstrings. 
* fixed wrongly formatted examples
* fixed wrong order of docstring elements 
* fixed wrong line highlights in the developer guide
* updated badges in the docs/index.md file according to current README.md file
Docs can be built again via `make docs`
> fix: docs build error

- docs/conf.py
This branch is adding the version switcher functionality to our docs. Additionally, a red warning banner is shown, when the user is viewing old docs versions. 
When rendering the docs locally, the switch works. However, when selecting a version from the switch, the docs are referring you to the actual deployed version of the current docs - at this point the version switch doesn't work anymore. 
Deployment info: 
* To make this version switcher work with previously deployed versions of the docs, the previous docs need to get rerendered
* As discussed with @JabobKrauskopf, rerendering the docs should be a one time manual task since the changes just affect some minor front-end functionalities and don't change any content
> docs: add version switcher

- medmodels/medrecord/_overview.py
Extracts attributes from medrecord in lists, so it can handle datatype attribute mismatches directly. 
Before there was a bug because of schema restrictions with polars.
> fix: attribute extraction without polars

- pyproject.toml
The last PR to update the polars version #308 was actually incorrect for two reasons:
1. The issue did not include that we should switch back to the old version instead
2. The issue incorrectly states that the version should be `<=` instead of the correct `>=`
> fix: polars version

- docs/_static/exec_literalinclude.css
- docs/sphinx_extensions.py
- docs/user_guide/02b_query_engine.md
- docs/user_guide/scripts/02b_query_engine.py
Adding an `Sphinx` extension that allows for showing errors when they are intended. Closes Issue #321 .
> docs: allow for errors to be thrown and shown in documentation

- pyproject.toml
Adding `scipy-stubs` as dependency to be able to lint `scipy` inputs/outputs correctly.
> build: add scipy and scipy-stubs

- crates/medmodels-core/src/medrecord/mod.rs
- crates/medmodels-core/src/medrecord/querying/mod.rs
- crates/medmodels-core/src/medrecord/querying/values/mod.rs
- medmodels/medrecord/medrecord.py
- medmodels/medrecord/querying.py
- medmodels/medrecord/types.py
- pyproject.toml
- rustmodels/src/medrecord/datatype.rs
- rustmodels/src/medrecord/mod.rs
- rustmodels/src/medrecord/querying/attributes.rs
- rustmodels/src/medrecord/querying/mod.rs
- rustmodels/src/medrecord/value.rs
- tests/medrecord/test_medrecord.py
- tests/medrecord/test_querying.py
- tests/medrecord/test_types.py
This PR refactors the rust return operand types. It also adds the possibility of returning multiple operands from queries. Getting the concrete return value type for these lists is quite difficult in python, so for new the generic return value type alias is returned and users will have to assert to get the concrete type (issue #404).
> refactor: query engine return types
